import type { EventDef } from '../../engine/types';
import {
  any,
  bond,
  chance,
  conflict,
  count,
  disc,
  employed,
  flag,
  happy,
  hasFlag,
  health,
  hobby,
  honesty,
  kindness,
  know,
  money,
  perf,
  removeNpc,
  rep,
  risk,
  schedule,
  schoolPerf,
  social,
  statMin,
  tag,
  trait,
  unflag,
} from './helpers';

// Ages 18-64: independence, work, love, family and money.

export const ADULT_EVENTS: EventDef[] = [
  {
    id: 'after_school',
    minAge: 17,
    maxAge: 21,
    weight: 0,
    scheduledOnly: true,
    choices: [
      { id: 'study', effects: [flag('focus_study'), know(3), disc(2)] },
      { id: 'work', effects: [flag('focus_work'), disc(2), rep(1)] },
      { id: 'gap', cost: 1500, effects: [happy(8), social(4), health(2), know(1)] },
      { id: 'slow', effects: [happy(2)] },
    ],
  },
  {
    id: 'roommate',
    minAge: 18,
    maxAge: 32,
    weight: 8,
    conditions: [{ type: 'housing', is: ['rent_small', 'rent_nice'] }],
    choices: [
      {
        id: 'confront',
        chance: chance(0.4, { stats: { social: 0.005 } }),
        success: [happy(3), social(2)],
        failure: [happy(-3), social(-1)],
      },
      { id: 'clean', effects: [disc(2), happy(-2)] },
      { id: 'chart', effects: [disc(3), social(1)] },
    ],
  },
  {
    id: 'campus_party',
    minAge: 18,
    maxAge: 26,
    weight: 10,
    conditions: [{ type: 'enrolled' }],
    choices: [
      {
        id: 'go',
        effects: [social(4), happy(3), schoolPerf(-5), health(-1), { type: 'addNpc', relation: 'friend', bond: 35, ageOffset: [-1, 2], tags: ['college_friend'] }],
      },
      { id: 'study', effects: [know(3), schoolPerf(6), happy(-1)] },
      { id: 'group', effects: [social(2), know(2), schoolPerf(4)] },
    ],
  },
  {
    id: 'meet_cute',
    chain: 'romance',
    minAge: 19,
    maxAge: 42,
    weight: 10,
    cooldown: 6,
    maxTimes: 2,
    conditions: [{ type: 'partner', not: true }],
    spawnNpc: { relation: 'friend', ageOffset: [-4, 4], bond: 30, tags: ['crush'] },
    choices: [
      {
        id: 'ask_out',
        chance: chance(0.3, { stats: { social: 0.005, reputation: 0.002 }, traits: { outgoing: 0.1, anxious: -0.1 } }),
        success: [{ type: 'npcRelation', relation: 'partner' }, bond('event', 25), happy(6)],
        failure: [happy(-3), bond('event', -10)],
      },
      { id: 'numbers', effects: [bond('event', 10), social(2)] },
      { id: 'leave', effects: [removeNpc, happy(-1)] },
    ],
  },
  {
    id: 'old_flame',
    chain: 'romance',
    minAge: 32,
    maxAge: 65,
    weight: 6,
    npc: { relation: 'ex', tag: 'old_flame' },
    choices: [
      { id: 'coffee', effects: [{ type: 'npcRelation', relation: 'friend' }, bond('event', 20), happy(3)] },
      {
        id: 'rekindle',
        requires: [{ type: 'partner', not: true }],
        chance: chance(0.3, { stats: { social: 0.004 } }),
        success: [{ type: 'npcRelation', relation: 'partner' }, bond('event', 30), happy(8)],
        failure: [happy(-4)],
      },
      { id: 'nod', effects: [disc(1)] },
    ],
  },
  {
    id: 'friend_startup',
    chain: 'childhood_friend',
    minAge: 24,
    maxAge: 46,
    weight: 0,
    scheduledOnly: true,
    npc: { relation: 'friend', tag: 'childhood_friend', minBond: 35 },
    choices: [
      {
        id: 'join',
        effects: [{ type: 'startJob', careerId: 'startup', level: 0 }, flag('joined_startup'), happy(4), bond('event', 10), schedule('startup_outcome', 3, 5, true)],
      },
      { id: 'invest', cost: 5000, effects: [flag('invested_startup'), bond('event', 8), risk, schedule('startup_outcome', 3, 5, true)] },
      { id: 'advice', effects: [bond('event', 4), rep(1), know(1)] },
      { id: 'decline', effects: [bond('event', -5)] },
    ],
  },
  {
    id: 'startup_outcome',
    chain: 'childhood_friend',
    minAge: 26,
    maxAge: 55,
    weight: 0,
    scheduledOnly: true,
    allowDeadNpc: true,
    conditions: [any(hasFlag('joined_startup'), hasFlag('invested_startup'))],
    choices: [
      {
        id: 'push',
        visibleIf: [{ type: 'employed', careerId: 'startup' }],
        chance: chance(0.35, { stats: { knowledge: 0.003, discipline: 0.002 } }),
        success: [money(250000), flag('entrepreneur'), rep(8), happy(10)],
        failure: [{ type: 'loseJob', reason: 'laidoff' }, happy(-8)],
      },
      {
        id: 'sell',
        visibleIf: [{ type: 'employed', careerId: 'startup' }],
        effects: [money(40000), flag('entrepreneur'), happy(3)],
      },
      {
        id: 'cash_out',
        visibleIf: [hasFlag('invested_startup')],
        chance: chance(0.5),
        success: [money(30000), happy(6)],
        failure: [happy(-5)],
      },
      { id: 'stand_by', effects: [bond('event', 10), happy(1)] },
    ],
  },
  {
    id: 'mentor_offer',
    chain: 'mentor',
    minAge: 22,
    maxAge: 38,
    weight: 8,
    conditions: [employed],
    spawnNpc: { relation: 'mentor', ageOffset: [20, 30], bond: 30 },
    choices: [
      { id: 'accept', effects: [flag('mentored'), bond('event', 20), perf(8), disc(2), schedule('mentor_farewell', 6, 12, true)] },
      { id: 'decline', effects: [removeNpc] },
      { id: 'compete', effects: [perf(5), happy(-2), removeNpc, flag('lone_wolf')] },
    ],
  },
  {
    id: 'mentor_farewell',
    chain: 'mentor',
    minAge: 28,
    maxAge: 55,
    weight: 0,
    scheduledOnly: true,
    npc: { relation: 'mentor' },
    choices: [
      {
        id: 'heartfelt',
        chance: chance(0.35, { stats: { social: 0.006 } }),
        success: [rep(6), happy(5), bond('event', 10)],
        failure: [happy(-2), bond('event', 5)],
      },
      {
        id: 'funny',
        chance: chance(0.3, { stats: { social: 0.006 }, traits: { outgoing: 0.1 } }),
        success: [social(4), rep(4)],
        failure: [rep(-3)],
      },
      { id: 'decline', effects: [bond('event', -10)] },
    ],
  },
  {
    id: 'shady_investment',
    chain: 'moonpenny',
    minAge: 23,
    maxAge: 55,
    weight: 7,
    conditions: [{ type: 'money', min: 2000 }],
    choices: [
      { id: 'buy_in', cost: 2000, effects: [money(5000), flag('moonpenny'), risk, schedule('moonpenny_probe', 2, 4)] },
      {
        id: 'recruit',
        cost: 2000,
        requires: [statMin('social', 50)],
        effects: [money(9000), bond('friends', -5), flag('moonpenny'), flag('moonpenny_recruiter'), risk, schedule('moonpenny_probe', 2, 4)],
      },
      { id: 'decline', effects: [disc(2)] },
      { id: 'report', effects: [rep(3), honesty] },
    ],
  },
  {
    id: 'moonpenny_probe',
    chain: 'moonpenny',
    minAge: 25,
    maxAge: 60,
    weight: 0,
    scheduledOnly: true,
    requiresFlags: ['moonpenny'],
    choices: [
      { id: 'cooperate', effects: [money(-4000), rep(-2), happy(-3), disc(2), honesty] },
      {
        id: 'lawyer',
        cost: 3000,
        chance: chance(0.6),
        success: [happy(1)],
        failure: [money(-8000), rep(-6), flag('criminal_record')],
      },
      {
        id: 'deny',
        chance: chance(0.3),
        success: [happy(2)],
        failure: [money(-10000), rep(-10), flag('criminal_record'), happy(-6)],
      },
      { id: 'apologize', visibleIf: [hasFlag('moonpenny_recruiter')], effects: [bond('friends', 8), money(-6000), rep(1)] },
    ],
  },
  {
    id: 'stress_habit',
    chain: 'smoking',
    minAge: 22,
    maxAge: 45,
    weight: 7,
    conditions: [employed],
    forbidsFlags: ['smoker', 'quit_smoking'],
    choices: [
      { id: 'smoke', effects: [flag('smoker'), happy(3), health(-2), risk, schedule('health_scare', 6, 12)] },
      { id: 'run', effects: [health(3), disc(2), happy(1), hobby('sports', 3)] },
      { id: 'vent', effects: [bond('friends', 3), happy(2)] },
    ],
  },
  {
    id: 'health_scare',
    chain: 'smoking',
    minAge: 28,
    maxAge: 75,
    weight: 0,
    scheduledOnly: true,
    requiresFlags: ['smoker'],
    choices: [
      { id: 'quit', effects: [unflag('smoker'), flag('quit_smoking'), disc(4), health(-2), schedule('recovery_milestone', 3, 5)] },
      { id: 'cut_down', effects: [health(-3), disc(1)] },
      { id: 'ignore', effects: [health(-6), happy(-2)] },
    ],
  },
  {
    id: 'recovery_milestone',
    chain: 'smoking',
    minAge: 30,
    maxAge: 85,
    weight: 0,
    scheduledOnly: true,
    tone: 'good',
    requiresFlags: ['quit_smoking'],
    forbidsFlags: ['smoker'],
    effects: [health(6), happy(4), money(800)],
  },
  {
    id: 'wedding_invite',
    minAge: 22,
    maxAge: 50,
    weight: 8,
    cooldown: 5,
    maxTimes: 3,
    npc: { relation: 'friend', minBond: 40 },
    choices: [
      { id: 'attend', cost: 400, effects: [bond('event', 12), happy(4), social(2)] },
      {
        id: 'speech',
        cost: 400,
        chance: chance(0.4, { stats: { social: 0.005 } }),
        success: [bond('event', 18), rep(3), happy(5)],
        failure: [bond('event', 5), happy(-3)],
      },
      { id: 'skip', effects: [bond('event', -8)] },
    ],
  },
  {
    id: 'car_breakdown',
    minAge: 18,
    maxAge: 80,
    weight: 7,
    cooldown: 6,
    maxTimes: 2,
    conditions: [any({ type: 'asset', asset: 'used_car' }, { type: 'asset', asset: 'new_car' })],
    choices: [
      { id: 'repair', cost: 1200, effects: [happy(-1)] },
      {
        id: 'diy',
        chance: chance(0.3, { stats: { knowledge: 0.004, discipline: 0.002 } }),
        success: [know(2), happy(3)],
        failure: [money(-1800), happy(-3)],
      },
      {
        id: 'sell',
        effects: [{ type: 'asset', asset: 'used_car', remove: true }, { type: 'asset', asset: 'new_car', remove: true }, money(800), happy(-2)],
      },
    ],
  },
  {
    id: 'boss_credit',
    minAge: 22,
    maxAge: 62,
    weight: 7,
    conditions: [employed],
    choices: [
      {
        id: 'confront',
        chance: chance(0.35, { stats: { social: 0.004, reputation: 0.003 } }),
        success: [rep(5), perf(6)],
        failure: [perf(-8), happy(-3)],
      },
      { id: 'let_go', effects: [happy(-3), disc(1)] },
      { id: 'document', effects: [disc(2), perf(3), rep(2)] },
    ],
  },
  {
    id: 'layoffs',
    minAge: 25,
    maxAge: 64,
    weight: 6,
    cooldown: 8,
    maxTimes: 2,
    conditions: [employed, { type: 'employed', careerId: 'startup', not: true }],
    choices: [
      { id: 'buyout', effects: [{ type: 'loseJob', reason: 'laidoff' }, money(10000), happy(-2)] },
      {
        id: 'harder',
        effects: [perf(10), health(-3), happy(-2)],
        chance: chance(0.75),
        success: [rep(1)],
        failure: [{ type: 'loseJob', reason: 'laidoff' }, happy(-6)],
      },
      {
        id: 'wait',
        chance: chance(0.6),
        success: [happy(1)],
        failure: [{ type: 'loseJob', reason: 'laidoff' }, happy(-6)],
      },
    ],
  },
  {
    id: 'side_business',
    chain: 'recipe',
    minAge: 25,
    maxAge: 55,
    weight: 8,
    conditions: [any(hasFlag('family_recipe'), { type: 'hobby', hobby: 'cooking', min: 40 })],
    choices: [
      { id: 'launch', cost: 1500, effects: [flag('side_business'), happy(3), schedule('market_success', 1, 3)] },
      { id: 'catering', effects: [money(600), health(-1), disc(1), hobby('cooking', 3)] },
      { id: 'family', effects: [bond('family', 4), happy(2)] },
    ],
  },
  {
    id: 'market_success',
    chain: 'recipe',
    minAge: 26,
    maxAge: 60,
    weight: 0,
    scheduledOnly: true,
    requiresFlags: ['side_business'],
    choices: [
      {
        id: 'expand',
        cost: 8000,
        chance: chance(0.4, { stats: { discipline: 0.003 }, hobbies: { cooking: 0.003 } }),
        success: [money(40000), flag('entrepreneur'), rep(6), happy(8)],
        failure: [money(-3000), happy(-5)],
      },
      { id: 'steady', effects: [money(6000), happy(3)] },
      { id: 'sell_recipe', effects: [money(15000), unflag('side_business'), happy(-1)] },
    ],
  },
  {
    id: 'sibling_loan',
    chain: 'sibling',
    minAge: 22,
    maxAge: 55,
    weight: 6,
    extraParams: () => ({ amount: { money: 3000 } }),
    npc: { relation: 'sibling', minBond: 20 },
    choices: [
      { id: 'lend', cost: 3000, effects: [bond('event', 10), flag('lent_sibling'), schedule('sibling_repay', 1, 3, true)] },
      { id: 'refuse', effects: [bond('event', -8), conflict('event', true)] },
      { id: 'help_job', effects: [bond('event', 6), social(1), rep(1)] },
    ],
  },
  {
    id: 'sibling_repay',
    chain: 'sibling',
    minAge: 23,
    maxAge: 60,
    weight: 0,
    scheduledOnly: true,
    npc: { relation: 'sibling' },
    choices: [
      {
        id: 'accept',
        chance: chance(0.6),
        success: [money(3300), happy(2), bond('event', 5)],
        failure: [happy(-2), bond('event', -3)],
      },
      { id: 'forgive', effects: [bond('event', 15), kindness, happy(2)] },
    ],
  },
  {
    id: 'sibling_reckoning',
    chain: 'sibling',
    minAge: 21,
    maxAge: 50,
    weight: 0,
    scheduledOnly: true,
    npc: { relation: 'sibling', pick: 'lowestBond' },
    choices: [
      { id: 'apologize', effects: [bond('event', 15), conflict('event', false), honesty, happy(3)] },
      {
        id: 'laugh',
        chance: chance(0.5, { stats: { social: 0.004 } }),
        success: [bond('event', 8), happy(3), conflict('event', false)],
        failure: [bond('event', -10), conflict('event', true)],
      },
      { id: 'deny', effects: [bond('event', -12), conflict('event', true)] },
    ],
  },
  {
    id: 'parent_illness',
    minAge: 28,
    maxAge: 70,
    weight: 7,
    npc: { relation: 'parent', minNpcAge: 65 },
    choices: [
      { id: 'care', effects: [bond('event', 15), perf(-8), happy(-3), health(-2), kindness, rep(2)] },
      { id: 'pay', cost: 5000, effects: [bond('event', 6), happy(1)] },
      { id: 'visit', effects: [bond('event', 3), happy(-1)] },
    ],
  },
  {
    id: 'parent_funeral',
    minAge: 0,
    maxAge: 120,
    weight: 0,
    maxTimes: 3,
    scheduledOnly: true,
    allowDeadNpc: true,
    choices: [
      {
        id: 'eulogy',
        visibleIf: [{ type: 'age', min: 12 }],
        chance: chance(0.4, { stats: { social: 0.005 } }),
        success: [rep(3), happy(2), bond('family', 5)],
        failure: [happy(-2), bond('family', 3)],
      },
      { id: 'quiet', effects: [happy(-2), disc(1)] },
      {
        id: 'reconcile',
        visibleIf: [{ type: 'npc', relation: 'sibling', conflict: true }],
        effects: [conflict('siblings', false), bond('siblings', 10), happy(3)],
      },
    ],
  },
  {
    id: 'marathon',
    minAge: 25,
    maxAge: 62,
    weight: 6,
    choices: [
      {
        id: 'train',
        requires: [statMin('health', 60)],
        chance: chance(0.3, { stats: { health: 0.004, discipline: 0.003 }, traits: { athletic: 0.15 } }),
        success: [flag('marathon'), health(5), happy(6), rep(2)],
        failure: [health(-3), happy(-2)],
      },
      { id: 'fun_run', effects: [health(2), happy(2), social(1)] },
      { id: 'couch', effects: [happy(1), health(-1)] },
    ],
  },
  {
    id: 'jury_duty',
    minAge: 21,
    maxAge: 70,
    weight: 5,
    choices: [
      { id: 'serve', effects: [disc(2), rep(2), happy(-1), know(1), perf(-2)] },
      {
        id: 'excuse',
        chance: chance(0.5),
        success: [happy(1)],
        failure: [rep(-2), disc(1)],
      },
    ],
  },
  {
    id: 'midlife_crisis',
    minAge: 40,
    maxAge: 52,
    weight: 8,
    choices: [
      { id: 'car', cost: 20000, requires: [hasFlag('license')], effects: [{ type: 'asset', asset: 'new_car' }, happy(8), rep(1)] },
      { id: 'learn', effects: [know(4), hobby('music', 6), happy(4)] },
      { id: 'sabbatical', cost: 3000, requires: [employed], effects: [{ type: 'loseJob', reason: 'quit' }, happy(10), health(3)] },
      { id: 'therapy', cost: 600, effects: [happy(6), trait('resilient')] },
    ],
  },
  {
    id: 'school_reunion',
    minAge: 35,
    maxAge: 45,
    weight: 8,
    choices: [
      { id: 'attend', effects: [social(3), happy(3)] },
      { id: 'apologize', visibleIf: [hasFlag('teased_kid')], effects: [rep(3), happy(4), honesty] },
      {
        id: 'brag',
        chance: chance(0.4, { stats: { reputation: 0.006 } }),
        success: [rep(3), happy(3)],
        failure: [social(-2), happy(-2)],
      },
      { id: 'skip', effects: [] },
    ],
  },
  {
    id: 'adopt_cat',
    minAge: 25,
    maxAge: 80,
    weight: 6,
    conditions: [{ type: 'npc', relation: 'pet', not: true }, { type: 'housing', is: ['family'], not: true }],
    spawnNpc: { relation: 'pet', age: [1, 4], bond: 30, species: 'cat' },
    choices: [
      { id: 'adopt', effects: [count('pets'), bond('event', 30), happy(5)] },
      { id: 'shelter', effects: [removeNpc, rep(1), kindness] },
    ],
  },
  {
    id: 'burnout',
    minAge: 26,
    maxAge: 62,
    weight: 10,
    cooldown: 6,
    maxTimes: 2,
    conditions: [employed, { type: 'stat', stat: 'happiness', max: 40 }],
    choices: [
      { id: 'leave', effects: [perf(-10), happy(8), health(3)] },
      { id: 'push', effects: [perf(6), health(-5), happy(-5)] },
      { id: 'quit', effects: [{ type: 'loseJob', reason: 'quit' }, happy(6)] },
    ],
  },
  {
    id: 'home_renovation',
    minAge: 25,
    maxAge: 85,
    weight: 6,
    conditions: [{ type: 'housing', is: ['own'] }],
    choices: [
      {
        id: 'diy',
        chance: chance(0.35, { stats: { discipline: 0.003, knowledge: 0.002 } }),
        success: [happy(5), know(2)],
        failure: [money(-2000), happy(-3), health(-1)],
      },
      { id: 'contractor', cost: 8000, effects: [happy(6)] },
      { id: 'leave', effects: [happy(-1)] },
    ],
  },
  {
    id: 'grandchild',
    minAge: 40,
    maxAge: 100,
    weight: 7,
    maxTimes: 3,
    cooldown: 3,
    tone: 'good',
    npc: { relation: 'child', minNpcAge: 22 },
    effects: [count('grandchildren'), happy(6), bond('event', 8)],
  },
  {
    id: 'child_school_trouble',
    minAge: 26,
    maxAge: 72,
    weight: 7,
    cooldown: 4,
    maxTimes: 2,
    npc: { relation: 'child', minNpcAge: 8, maxNpcAge: 16 },
    choices: [
      { id: 'talk', effects: [bond('event', 8), happy(1)] },
      { id: 'punish', effects: [bond('event', -6), happy(-1)] },
      { id: 'ignore', effects: [bond('event', -4)] },
    ],
  },
  {
    id: 'child_college',
    minAge: 35,
    maxAge: 75,
    weight: 12,
    maxTimes: 3,
    cooldown: 1,
    // Each child gets this decision once.
    npc: { relation: 'child', minNpcAge: 17, maxNpcAge: 19, notTag: 'college_decided' },
    choices: [
      { id: 'pay', cost: 20000, effects: [bond('event', 15), happy(4), tag('college_decided')] },
      { id: 'half', cost: 8000, effects: [bond('event', 8), tag('college_decided')] },
      { id: 'own_way', effects: [bond('event', -3), tag('college_decided')] },
    ],
  },
  { id: 'lottery_scratch', minAge: 18, maxAge: 95, weight: 2, tone: 'good', effects: [money(500), happy(3)] },
  {
    id: 'noisy_neighbors',
    minAge: 18,
    maxAge: 85,
    weight: 6,
    conditions: [{ type: 'housing', is: ['family'], not: true }],
    choices: [
      {
        id: 'complain',
        chance: chance(0.5, { stats: { social: 0.004 } }),
        success: [happy(2)],
        failure: [happy(-2), rep(-1)],
      },
      { id: 'join', effects: [social(3), happy(2), health(-1)] },
      { id: 'earplugs', cost: 20, effects: [happy(-1), disc(1)] },
    ],
  },
  {
    id: 'retirement_offer',
    minAge: 60,
    maxAge: 90,
    weight: 0,
    scheduledOnly: true,
    conditions: [employed],
    choices: [
      { id: 'retire', effects: [{ type: 'retire' }, happy(6)] },
      { id: 'continue', effects: [perf(2), disc(1), rep(1)] },
    ],
  },
  { id: 'blackout', minAge: 14, maxAge: 95, weight: 4, tone: 'good', effects: [social(2), happy(2)] },
  {
    id: 'record_surfaces',
    chain: 'shoplift',
    minAge: 20,
    maxAge: 45,
    weight: 0,
    scheduledOnly: true,
    requiresFlags: ['shoplift_report'],
    choices: [
      {
        id: 'explain',
        chance: chance(0.4, { stats: { social: 0.004, reputation: 0.003 } }),
        success: [rep(2), happy(2), honesty],
        failure: [rep(-3), happy(-3)],
      },
      {
        id: 'hide',
        chance: chance(0.4),
        success: [happy(1)],
        failure: [rep(-8), perf(-10), happy(-5)],
      },
    ],
  },
  {
    id: 'old_secret',
    chain: 'shoplift',
    minAge: 25,
    maxAge: 50,
    weight: 0,
    scheduledOnly: true,
    requiresFlags: ['shoplifted'],
    choices: [
      { id: 'pay_back', cost: 100, effects: [happy(4), honesty, rep(1)] },
      { id: 'souvenir', cost: 20, effects: [happy(2)] },
      { id: 'walk_by', effects: [happy(-1)] },
    ],
  },
  {
    id: 'parent_advice',
    minAge: 18,
    maxAge: 35,
    weight: 6,
    tone: 'good',
    npc: { relation: 'parent', minBond: 60 },
    effects: [happy(4), bond('event', 3)],
  },
  {
    id: 'friend_moves_away',
    minAge: 14,
    maxAge: 60,
    weight: 6,
    cooldown: 6,
    maxTimes: 2,
    npc: { relation: 'friend', minBond: 30 },
    choices: [
      { id: 'promise', effects: [bond('event', 6), disc(1)] },
      { id: 'party', effects: [social(3), bond('event', 8), happy(2)] },
      { id: 'shrug', effects: [bond('event', -10)] },
    ],
  },
  {
    id: 'relocation_offer',
    minAge: 25,
    maxAge: 55,
    weight: 6,
    conditions: [employed, { type: 'employed', careerId: 'startup', not: true }],
    choices: [
      { id: 'accept', effects: [{ type: 'promote' }, perf(5), bond('friends', -8), bond('parents', -4), happy(2)] },
      { id: 'decline', effects: [bond('family', 4), happy(1)] },
    ],
  },
  { id: 'bad_flu', minAge: 18, maxAge: 100, weight: 5, cooldown: 5, maxTimes: 4, tone: 'bad', effects: [health(-4), happy(-2), perf(-3)] },
  {
    id: 'hobby_spotlight',
    minAge: 18,
    maxAge: 90,
    weight: 6,
    tone: 'good',
    conditions: [
      any(
        { type: 'hobby', hobby: 'music', min: 50 },
        { type: 'hobby', hobby: 'art', min: 50 },
        { type: 'hobby', hobby: 'writing', min: 50 },
        { type: 'hobby', hobby: 'cooking', min: 50 },
        { type: 'hobby', hobby: 'gardening', min: 50 },
      ),
    ],
    effects: [rep(3), happy(3)],
  },
];
