import type { EventDef } from '../../engine/types';
import {
  any,
  bond,
  chance,
  conflict,
  count,
  disc,
  flag,
  happy,
  health,
  hobby,
  honesty,
  inSchool,
  kindness,
  know,
  money,
  removeNpc,
  rep,
  risk,
  schedule,
  schoolPerf,
  social,
  tag,
} from './helpers';

// Ages 0-12. Text keys: ev.<id>.title / .text / .c.<choice> / .r.<choice>[_ok|_fail]

export const CHILDHOOD_EVENTS: EventDef[] = [
  {
    id: 'first_word',
    minAge: 1,
    maxAge: 2,
    weight: 10,
    tone: 'good',
    effects: [happy(2), know(1)],
    extraParams: (_s, pick) => ({ word: { t: `word.${pick(['ball', 'moon', 'cookie', 'dog', 'no', 'more'] as const)}` } }),
  },
  {
    id: 'first_steps',
    minAge: 1,
    maxAge: 2,
    weight: 10,
    tone: 'good',
    effects: [happy(2), disc(1), health(-1)],
  },
  {
    id: 'toddler_tantrum',
    minAge: 2,
    maxAge: 4,
    weight: 10,
    choices: [
      { id: 'scream', effects: [happy(2), bond('parents', -3), rep(-1)] },
      { id: 'ask', effects: [social(2), disc(2), bond('parents', 2)] },
      {
        id: 'sneak',
        effects: [risk],
        chance: chance(0.4, { stats: { discipline: 0.004 } }),
        success: [happy(4)],
        failure: [happy(-2), bond('parents', -2)],
      },
    ],
  },
  {
    id: 'imaginary_friend',
    minAge: 3,
    maxAge: 6,
    weight: 8,
    choices: [
      { id: 'keep', effects: [happy(3), hobby('art', 4), flag('imaginative')] },
      { id: 'introduce', effects: [bond('parents', 3), social(1)] },
      { id: 'let_go', effects: [disc(2)] },
    ],
  },
  {
    id: 'first_day_school',
    minAge: 6,
    maxAge: 7,
    weight: 30,
    conditions: [inSchool],
    choices: [
      { id: 'cling', effects: [happy(-2), bond('parents', 2)] },
      {
        id: 'stranger',
        effects: [social(3), { type: 'addNpc', relation: 'friend', bond: 40, ageOffset: [0, 0], tags: ['school_friend'] }],
      },
      { id: 'explore', effects: [know(3), disc(-1)] },
    ],
  },
  {
    id: 'new_kid',
    chain: 'childhood_friend',
    minAge: 7,
    maxAge: 10,
    weight: 14,
    conditions: [inSchool],
    spawnNpc: { relation: 'friend', ageOffset: [0, 0], bond: 25, tags: ['new_kid'] },
    choices: [
      {
        id: 'invite',
        effects: [
          bond('event', 25),
          social(2),
          happy(2),
          tag('childhood_friend'),
          flag('befriended_new_kid'),
          kindness,
          schedule('friend_in_trouble', 5, 7, true),
        ],
      },
      { id: 'wave', effects: [bond('event', 5), social(1)] },
      { id: 'ignore', effects: [removeNpc] },
      { id: 'tease', effects: [removeNpc, flag('teased_kid'), rep(-2), social(1)] },
    ],
  },
  { id: 'lost_tooth', minAge: 6, maxAge: 8, weight: 8, tone: 'good', effects: [money(5), happy(2)] },
  {
    id: 'science_fair',
    chain: 'science',
    minAge: 9,
    maxAge: 12,
    weight: 12,
    conditions: [inSchool],
    choices: [
      {
        id: 'work_hard',
        effects: [know(4), disc(3), happy(-1), schoolPerf(8)],
        chance: chance(0.3, { stats: { knowledge: 0.006, discipline: 0.004 }, traits: { curious: 0.1 } }),
        success: [flag('science_star'), rep(3), happy(4)],
        failure: [know(2), happy(-1)],
      },
      { id: 'kit', effects: [bond('parents', -1), know(2), rep(1)] },
      { id: 'parent', effects: [bond('parents', 2), disc(-2), rep(-1)] },
    ],
  },
  {
    id: 'stray_puppy',
    chain: 'pet',
    minAge: 6,
    maxAge: 12,
    weight: 10,
    conditions: [{ type: 'npc', relation: 'pet', not: true }],
    spawnNpc: { relation: 'pet', age: [0, 1], bond: 40, species: 'dog' },
    choices: [
      {
        id: 'adopt',
        effects: [tag('first_pet'), bond('event', 30), happy(6), count('pets'), disc(1), schedule('pet_old_age', 10, 12, true)],
      },
      { id: 'shelter', effects: [removeNpc, rep(2), kindness, happy(-1)] },
      { id: 'shoo', effects: [removeNpc, happy(-2)] },
    ],
  },
  {
    id: 'dream_job',
    chain: 'dream',
    minAge: 7,
    maxAge: 10,
    weight: 14,
    conditions: [inSchool],
    choices: [
      { id: 'doctor', effects: [flag('dream_health'), know(1)] },
      { id: 'artist', effects: [flag('dream_creative'), hobby('art', 5)] },
      { id: 'inventor', effects: [flag('dream_tech'), know(2)] },
      { id: 'teacher', effects: [flag('dream_teach'), social(1)] },
    ],
  },
  {
    id: 'time_capsule',
    chain: 'dream',
    minAge: 10,
    maxAge: 12,
    weight: 14,
    conditions: [
      inSchool,
      any(
        { type: 'flag', flag: 'dream_health' },
        { type: 'flag', flag: 'dream_creative' },
        { type: 'flag', flag: 'dream_tech' },
        { type: 'flag', flag: 'dream_teach' },
      ),
    ],
    choices: [
      { id: 'letter', effects: [flag('capsule_letter'), disc(1), schedule('time_capsule_open', 19, 21)] },
      { id: 'toy', effects: [flag('capsule_toy'), happy(-1), schedule('time_capsule_open', 19, 21)] },
      { id: 'skip', effects: [happy(1)] },
    ],
  },
  {
    id: 'neighbor_groceries',
    chain: 'neighbor',
    minAge: 8,
    maxAge: 12,
    weight: 10,
    spawnNpc: { relation: 'friend', ageOffset: [62, 70], bond: 20, tags: ['neighbor'] },
    choices: [
      {
        id: 'help',
        effects: [bond('event', 20), rep(2), happy(2), kindness, flag('helped_neighbor'), schedule('neighbor_legacy', 6, 12, true)],
      },
      { id: 'pretend', effects: [removeNpc, happy(-1)] },
      { id: 'charge', effects: [money(5), bond('event', 3), disc(1), flag('young_hustler'), removeNpc] },
    ],
  },
  {
    id: 'broken_window',
    chain: 'sibling',
    minAge: 7,
    maxAge: 12,
    weight: 10,
    choices: [
      { id: 'confess', effects: [rep(2), disc(2), bond('parents', 1), honesty] },
      {
        id: 'run',
        effects: [risk],
        chance: chance(0.6),
        success: [happy(1)],
        failure: [rep(-3), bond('parents', -3)],
      },
      {
        id: 'blame',
        visibleIf: [{ type: 'npc', relation: 'sibling' }],
        effects: [bond('siblings', -10), conflict('siblings', true), flag('blamed_sibling'), happy(1), schedule('sibling_reckoning', 14, 25)],
      },
    ],
  },
  {
    id: 'bully',
    minAge: 8,
    maxAge: 13,
    weight: 10,
    choices: [
      {
        id: 'stand_up',
        chance: chance(0.3, { stats: { health: 0.003, social: 0.003 }, traits: { athletic: 0.15, reckless: 0.05 } }),
        success: [rep(4), happy(3), flag('stood_up')],
        failure: [health(-4), happy(-3), rep(1)],
      },
      { id: 'tell', effects: [happy(2), rep(-1)] },
      { id: 'avoid', effects: [happy(-2), social(-1), disc(1)] },
      {
        id: 'befriend',
        chance: chance(0.25, { stats: { social: 0.005 }, traits: { kind: 0.1 } }),
        success: [{ type: 'addNpc', relation: 'friend', bond: 35, ageOffset: [1, 2], tags: ['former_bully'] }, social(2)],
        failure: [happy(-3)],
      },
    ],
  },
  {
    id: 'school_play',
    minAge: 8,
    maxAge: 12,
    weight: 8,
    conditions: [inSchool],
    choices: [
      {
        id: 'audition',
        chance: chance(0.3, { stats: { social: 0.006 }, traits: { creative: 0.15, outgoing: 0.1 } }),
        success: [rep(4), social(4), happy(4)],
        failure: [social(1), happy(-2)],
      },
      { id: 'backstage', effects: [disc(2), hobby('art', 4), social(1)] },
      { id: 'skip', effects: [happy(1)] },
    ],
  },
  { id: 'chickenpox', minAge: 3, maxAge: 10, weight: 6, tone: 'bad', effects: [health(-4), happy(-3)] },
  {
    id: 'found_wallet',
    minAge: 9,
    maxAge: 16,
    weight: 8,
    choices: [
      { id: 'return', effects: [rep(4), happy(2), honesty] },
      { id: 'keep', effects: [money(40), disc(-2), happy(-1), risk] },
      { id: 'leave', effects: [] },
    ],
  },
  {
    id: 'grandparent_recipe',
    chain: 'recipe',
    minAge: 6,
    maxAge: 12,
    weight: 9,
    npc: { relation: 'grandparent', pick: 'highestBond' },
    choices: [
      { id: 'learn', effects: [hobby('cooking', 10), bond('event', 10), flag('family_recipe'), disc(1)] },
      { id: 'later', effects: [bond('event', -3)] },
    ],
  },
  {
    id: 'spelling_bee',
    minAge: 8,
    maxAge: 11,
    weight: 8,
    conditions: [inSchool],
    choices: [
      {
        id: 'practice',
        effects: [know(2)],
        chance: chance(0.2, { stats: { knowledge: 0.008, discipline: 0.003 } }),
        success: [rep(4), happy(4)],
        failure: [happy(-1)],
      },
      {
        id: 'wing_it',
        chance: chance(0.1, { stats: { knowledge: 0.006 } }),
        success: [rep(3), happy(5)],
        failure: [happy(-3), rep(-1)],
      },
      { id: 'skip', effects: [] },
    ],
  },
  {
    id: 'parent_job_loss',
    minAge: 5,
    maxAge: 14,
    weight: 6,
    npc: { relation: 'parent', maxNpcAge: 64 },
    choices: [
      { id: 'savings', effects: [{ type: 'moneyPct', pct: -1 }, bond('event', 12), kindness, happy(-1)] },
      { id: 'cheer', effects: [bond('event', 6), happy(1), social(1)] },
      { id: 'quiet', effects: [happy(-2)] },
    ],
  },
  {
    id: 'summer_camp',
    minAge: 8,
    maxAge: 13,
    weight: 8,
    choices: [
      { id: 'sports', effects: [health(4), social(2), hobby('sports', 6)] },
      { id: 'science', effects: [know(4), disc(1)] },
      { id: 'music', effects: [hobby('music', 6), happy(2)] },
      { id: 'home', effects: [happy(1), bond('parents', 2)] },
    ],
  },
  {
    id: 'new_sibling',
    minAge: 1,
    maxAge: 10,
    weight: 5,
    tone: 'good',
    conditions: [{ type: 'npc', relation: 'parent', maxNpcAge: 42 }],
    spawnNpc: { relation: 'sibling', age: [0, 0], bond: 55, sameSurname: true },
    effects: [happy(2), bond('parents', -1)],
  },
  {
    id: 'sleepover',
    minAge: 7,
    maxAge: 12,
    weight: 8,
    npc: { relation: 'friend', maxNpcAge: 14 },
    choices: [
      { id: 'go', effects: [bond('event', 8), social(2), happy(3), health(-1)] },
      { id: 'host', effects: [bond('event', 6), bond('parents', 1), social(2)] },
      { id: 'decline', effects: [happy(-1), bond('event', -2)] },
    ],
  },
  { id: 'museum_trip', minAge: 6, maxAge: 12, weight: 6, tone: 'good', conditions: [inSchool], effects: [know(3), happy(2)] },
  { id: 'learn_bike', minAge: 5, maxAge: 8, weight: 7, tone: 'good', effects: [health(2), happy(3), disc(1)] },
];
