import type { EventDef } from '../../engine/types';
import {
  bond,
  count,
  disc,
  flag,
  happy,
  hasFlag,
  health,
  hobby,
  killNpc,
  kindness,
  know,
  money,
  rep,
  schedule,
  social,
} from './helpers';

// Later life (and the long-term payoffs of earlier chains).

export const ELDER_EVENTS: EventDef[] = [
  {
    id: 'retirement_hobby',
    minAge: 60,
    maxAge: 85,
    weight: 10,
    conditions: [{ type: 'retired' }],
    choices: [
      { id: 'garden', effects: [hobby('gardening', 10), health(2), happy(3)] },
      { id: 'travel', cost: 3000, effects: [happy(8), count('trips'), health(1)] },
      { id: 'volunteer', effects: [rep(4), social(3), kindness] },
    ],
  },
  {
    id: 'grandkid_visit',
    minAge: 55,
    maxAge: 100,
    weight: 8,
    cooldown: 5,
    maxTimes: 3,
    conditions: [{ type: 'counter', counter: 'grandchildren', min: 1 }],
    choices: [
      { id: 'teach', effects: [bond('children', 5), happy(4), rep(1)] },
      { id: 'spoil', cost: 200, effects: [happy(5), bond('children', 2)] },
      { id: 'nap', effects: [health(2), happy(1)] },
    ],
  },
  {
    id: 'scam_call',
    minAge: 65,
    maxAge: 105,
    weight: 7,
    choices: [
      { id: 'give', effects: [{ type: 'moneyPct', pct: -0.15, max: 15000 }, happy(-4)] },
      { id: 'hang_up', effects: [disc(1), happy(1)] },
      { id: 'call_family', effects: [bond('family', 3), happy(2), social(1)] },
    ],
  },
  {
    id: 'memoir',
    minAge: 62,
    maxAge: 95,
    weight: 7,
    choices: [
      { id: 'write', effects: [hobby('writing', 12), know(2), flag('memoir'), schedule('memoir_published', 2, 4)] },
      { id: 'record', effects: [bond('family', 5), happy(3)] },
      { id: 'no', effects: [] },
    ],
  },
  {
    id: 'memoir_published',
    minAge: 64,
    maxAge: 105,
    weight: 0,
    scheduledOnly: true,
    requiresFlags: ['memoir'],
    conditions: [{ type: 'hobby', hobby: 'writing', min: 30 }],
    choices: [
      { id: 'publish', effects: [rep(6), happy(8), money(2000)] },
      { id: 'family_only', effects: [bond('family', 8), happy(4)] },
    ],
  },
  { id: 'fall_injury', minAge: 72, maxAge: 115, weight: 6, cooldown: 4, maxTimes: 3, tone: 'bad', effects: [health(-6), happy(-3)] },
  {
    id: 'old_friend_letter',
    chain: 'childhood_friend',
    minAge: 65,
    maxAge: 105,
    weight: 12,
    npc: { relation: 'friend', tag: 'childhood_friend' },
    choices: [
      { id: 'visit', cost: 500, effects: [bond('event', 15), happy(8), health(1)] },
      { id: 'reply', effects: [bond('event', 8), happy(4)] },
      { id: 'keep', effects: [happy(2)] },
    ],
  },
  {
    id: 'mentor_young',
    chain: 'mentor',
    minAge: 60,
    maxAge: 90,
    weight: 10,
    requiresFlags: ['mentored'],
    choices: [
      { id: 'mentor', effects: [flag('mentored_someone'), rep(5), happy(6)] },
      { id: 'advice', effects: [happy(2), rep(1)] },
      { id: 'busy', effects: [] },
    ],
  },
  {
    id: 'downsizing',
    minAge: 65,
    maxAge: 95,
    weight: 7,
    conditions: [{ type: 'housing', is: ['own'] }],
    choices: [
      { id: 'sell', effects: [{ type: 'sellHome' }, happy(-1), disc(1)] },
      { id: 'stay', effects: [happy(2)] },
    ],
  },
  {
    id: 'tech_class',
    minAge: 65,
    maxAge: 100,
    weight: 6,
    choices: [
      { id: 'enroll', effects: [know(3), social(2), happy(2)] },
      { id: 'refuse', effects: [happy(1), know(-1)] },
    ],
  },
  { id: 'centenarian_party', minAge: 100, maxAge: 100, weight: 100, tone: 'milestone', effects: [happy(10), rep(5)] },
  {
    id: 'pet_old_age',
    chain: 'pet',
    minAge: 14,
    maxAge: 40,
    weight: 0,
    scheduledOnly: true,
    npc: { relation: 'pet', tag: 'first_pet' },
    choices: [
      { id: 'beach', effects: [killNpc, happy(-3), flag('pet_memory')] },
      { id: 'vet', cost: 1500, effects: [happy(2), bond('event', 5), schedule('pet_goodbye', 1, 2, true)] },
    ],
  },
  {
    id: 'pet_goodbye',
    chain: 'pet',
    minAge: 15,
    maxAge: 45,
    weight: 0,
    scheduledOnly: true,
    tone: 'bad',
    npc: { relation: 'pet' },
    effects: [killNpc, happy(-5), flag('pet_memory')],
  },
  {
    id: 'time_capsule_open',
    chain: 'dream',
    minAge: 28,
    maxAge: 36,
    weight: 0,
    scheduledOnly: true,
    extraParams: (state) => ({ item: { t: Object.prototype.hasOwnProperty.call(state.flags, 'capsule_letter') ? 'capsule.letter' : 'capsule.toy' } }),
    choices: [
      { id: 'dream_lived', requires: [{ type: 'dreamJob' }], effects: [happy(10), rep(3), flag('dream_honored')] },
      { id: 'laugh', effects: [happy(4), social(2)] },
      { id: 'new_dream', effects: [disc(2), happy(2), know(1)] },
    ],
  },
  {
    id: 'neighbor_legacy',
    chain: 'neighbor',
    minAge: 14,
    maxAge: 30,
    weight: 0,
    scheduledOnly: true,
    allowDeadNpc: true,
    onStart: [killNpc],
    choices: [
      { id: 'keep', effects: [{ type: 'asset', asset: 'instrument' }, hobby('music', 5), happy(3)] },
      { id: 'sell', effects: [money(1500)] },
      { id: 'donate', effects: [rep(3), kindness, happy(1)] },
    ],
  },
  {
    id: 'sunset_walk',
    minAge: 70,
    maxAge: 110,
    weight: 5,
    tone: 'good',
    effects: [happy(3), health(1)],
  },
  {
    id: 'old_photos',
    minAge: 60,
    maxAge: 110,
    weight: 5,
    tone: 'good',
    conditions: [hasFlag('befriended_new_kid')],
    effects: [happy(3), social(1)],
  },
];
