import type { EventDef } from '../../engine/types';
import {
  any,
  bond,
  chance,
  count,
  disc,
  flag,
  happy,
  health,
  hobby,
  honesty,
  inSchool,
  kindness,
  know,
  money,
  rep,
  risk,
  schedule,
  schoolPerf,
  social,
  statMin,
  unemployed,
  unflag,
} from './helpers';

// Ages 12-19 (plus the band follow-ups).

export const TEEN_EVENTS: EventDef[] = [
  {
    id: 'first_phone',
    minAge: 12,
    maxAge: 14,
    weight: 14,
    choices: [
      { id: 'all_in', effects: [social(4), happy(2), disc(-3), know(-1), flag('screen_heavy')] },
      { id: 'balanced', effects: [disc(2), social(2)] },
      { id: 'decline', effects: [know(2), social(-2), disc(2)] },
    ],
  },
  {
    id: 'exam_cheat',
    minAge: 13,
    maxAge: 17,
    weight: 9,
    conditions: [inSchool],
    choices: [
      {
        id: 'cheat',
        effects: [risk],
        chance: chance(0.7, { traits: { reckless: -0.1 } }),
        success: [schoolPerf(12), disc(-3)],
        failure: [schoolPerf(-15), rep(-5), flag('caught_cheating'), bond('parents', -5)],
      },
      { id: 'study', effects: [know(3), health(-2), schoolPerf(6), disc(2)] },
      { id: 'report', effects: [rep(3), social(-3), honesty] },
    ],
  },
  {
    id: 'house_party',
    minAge: 15,
    maxAge: 17,
    weight: 9,
    choices: [
      {
        id: 'wild',
        effects: [social(5), happy(4), health(-3), risk],
        chance: chance(0.7),
        success: [],
        failure: [bond('parents', -8), rep(-3)],
      },
      { id: 'early', effects: [social(3), happy(2), disc(1)] },
      { id: 'stay', effects: [know(2), happy(-1)] },
    ],
  },
  {
    id: 'dare_shoplift',
    chain: 'shoplift',
    minAge: 13,
    maxAge: 16,
    weight: 8,
    choices: [
      {
        id: 'do_it',
        effects: [risk],
        chance: chance(0.65, { stats: { discipline: -0.002 } }),
        success: [social(4), happy(2), flag('shoplifted'), schedule('old_secret', 15, 25)],
        failure: [rep(-6), bond('parents', -8), flag('shoplift_report'), schedule('record_surfaces', 7, 14)],
      },
      { id: 'refuse', effects: [social(-2), disc(2), rep(1), honesty] },
      { id: 'pay', cost: 2, effects: [social(2), happy(1)] },
    ],
  },
  {
    id: 'start_band',
    chain: 'band',
    minAge: 13,
    maxAge: 17,
    weight: 8,
    choices: [
      { id: 'join', effects: [hobby('music', 8), social(3), happy(3), flag('band_member'), schedule('band_gig', 1, 3)] },
      { id: 'manage', effects: [social(2), disc(2), rep(1), flag('band_manager'), schedule('band_gig', 1, 3)] },
      { id: 'decline', effects: [know(1)] },
    ],
  },
  {
    id: 'band_gig',
    chain: 'band',
    minAge: 14,
    maxAge: 21,
    weight: 0,
    scheduledOnly: true,
    conditions: [any({ type: 'flag', flag: 'band_member' }, { type: 'flag', flag: 'band_manager' })],
    choices: [
      {
        id: 'originals',
        effects: [schedule('band_reunion', 15, 25)],
        chance: chance(0.35, { hobbies: { music: 0.006 }, stats: { social: 0.002 } }),
        success: [rep(4), happy(6), hobby('music', 4), flag('band_success')],
        failure: [happy(-3), social(1)],
      },
      { id: 'covers', effects: [happy(3), social(2), schedule('band_reunion', 15, 25)] },
      { id: 'quit', effects: [unflag('band_member'), unflag('band_manager'), happy(-1), disc(1)] },
    ],
  },
  {
    id: 'band_reunion',
    chain: 'band',
    minAge: 30,
    maxAge: 55,
    weight: 0,
    scheduledOnly: true,
    choices: [
      { id: 'reunite', effects: [happy(8), social(3), money(2000), hobby('music', 3)] },
      {
        id: 'pitch',
        requires: [{ type: 'hobby', hobby: 'music', min: 60 }],
        chance: chance(0.4, { hobbies: { music: 0.004 }, stats: { reputation: 0.002 } }),
        success: [flag('record_deal'), money(15000), rep(10), happy(10)],
        failure: [happy(-3), hobby('music', 2)],
      },
      { id: 'decline', effects: [happy(-1)] },
    ],
  },
  {
    id: 'part_time_offer',
    minAge: 15,
    maxAge: 17,
    weight: 9,
    conditions: [inSchool, unemployed],
    choices: [
      { id: 'shop', effects: [{ type: 'startJob', careerId: 'retail', level: 0 }, disc(2)] },
      { id: 'kitchen', effects: [{ type: 'startJob', careerId: 'kitchen', level: 0 }, disc(2), hobby('cooking', 3)] },
      { id: 'decline', effects: [happy(1)] },
    ],
  },
  {
    id: 'friend_in_trouble',
    chain: 'childhood_friend',
    minAge: 12,
    maxAge: 19,
    weight: 0,
    scheduledOnly: true,
    npc: { relation: 'friend', tag: 'childhood_friend' },
    choices: [
      { id: 'host', effects: [bond('parents', -3), bond('event', 20), kindness, flag('helped_friend'), schedule('friend_startup', 10, 18, true)] },
      { id: 'lend', effects: [{ type: 'moneyPct', pct: -0.5 }, bond('event', 12), schedule('friend_startup', 10, 18, true)] },
      { id: 'adult', effects: [bond('event', 5), rep(2), schedule('friend_startup', 10, 18, true)] },
      { id: 'refuse', effects: [bond('event', -15), happy(-2)] },
    ],
  },
  {
    id: 'scholarship_competition',
    chain: 'science',
    minAge: 16,
    maxAge: 17,
    weight: 14,
    conditions: [inSchool, any({ type: 'flag', flag: 'science_star' }, statMin('knowledge', 70))],
    choices: [
      {
        id: 'prepare',
        effects: [know(3)],
        chance: chance(0.2, { stats: { knowledge: 0.006, discipline: 0.003 }, traits: { curious: 0.1 } }),
        success: [{ type: 'scholarship', amount: 0.75 }, flag('scholarship_winner'), rep(5), happy(6)],
        failure: [happy(-2)],
      },
      {
        id: 'relaxed',
        chance: chance(0.1, { stats: { knowledge: 0.005 } }),
        success: [{ type: 'scholarship', amount: 0.5 }, flag('scholarship_winner'), rep(3), happy(5)],
        failure: [happy(-1)],
      },
      { id: 'skip', effects: [happy(1)] },
    ],
  },
  {
    id: 'driving_lesson',
    minAge: 15,
    maxAge: 17,
    weight: 8,
    conditions: [{ type: 'flag', flag: 'license', not: true }],
    npc: { relation: 'parent', pick: 'highestBond' },
    choices: [
      { id: 'careful', effects: [disc(2), bond('event', 5), count('licenseAttempts')] },
      {
        id: 'fast',
        effects: [risk],
        chance: chance(0.6, { traits: { reckless: -0.1 } }),
        success: [happy(3), bond('event', 2)],
        failure: [health(-2), bond('event', -5)],
      },
      { id: 'later', effects: [] },
    ],
  },
  {
    id: 'sports_tryout',
    minAge: 13,
    maxAge: 16,
    weight: 9,
    choices: [
      {
        id: 'tryout',
        chance: chance(0.25, { stats: { health: 0.004 }, hobbies: { sports: 0.005 }, traits: { athletic: 0.15 } }),
        success: [health(4), social(3), rep(3), hobby('sports', 8), flag('team_player')],
        failure: [happy(-3), disc(2)],
      },
      { id: 'cheer', effects: [social(2), happy(1)] },
      { id: 'skip', effects: [know(1)] },
    ],
  },
  {
    id: 'dropout_temptation',
    minAge: 16,
    maxAge: 17,
    weight: 10,
    conditions: [inSchool, any({ type: 'schoolPerf', max: 45 }, { type: 'stat', stat: 'happiness', max: 35 })],
    choices: [
      {
        id: 'drop',
        effects: [{ type: 'dropOut' }, { type: 'startJob', careerId: 'warehouse', level: 0 }, happy(3), rep(-3), bond('parents', -10)],
      },
      { id: 'stay', effects: [disc(3), happy(-2), schoolPerf(5)] },
      { id: 'counselor', effects: [social(1), happy(3), schoolPerf(8), disc(1)] },
    ],
  },
  { id: 'picture_day', minAge: 13, maxAge: 16, weight: 6, tone: 'neutral', effects: [happy(-2), social(1)] },
  {
    id: 'volunteer_shelter',
    minAge: 14,
    maxAge: 18,
    weight: 7,
    choices: [
      { id: 'animals', effects: [happy(3), rep(2), kindness] },
      { id: 'food_bank', effects: [rep(3), social(2), kindness] },
      { id: 'busy', effects: [disc(1)] },
    ],
  },
  {
    id: 'viral_video',
    minAge: 13,
    maxAge: 19,
    weight: 6,
    choices: [
      {
        id: 'lean_in',
        chance: chance(0.5, { stats: { social: 0.003 } }),
        success: [social(5), rep(4), happy(4), money(300)],
        failure: [rep(-3), happy(-3)],
      },
      { id: 'delete', effects: [happy(-1), disc(1)] },
      { id: 'laugh', effects: [happy(2), social(2)] },
    ],
  },
  {
    id: 'career_fair',
    minAge: 15,
    maxAge: 17,
    weight: 10,
    conditions: [inSchool],
    choices: [
      { id: 'tech', effects: [know(2), flag('interest_tech')] },
      { id: 'health', effects: [social(1), flag('interest_health')] },
      { id: 'trades', effects: [disc(1), flag('interest_trades')] },
      { id: 'people', effects: [social(1), flag('interest_people')] },
    ],
  },
  {
    id: 'talent_show',
    minAge: 13,
    maxAge: 17,
    weight: 7,
    conditions: [inSchool],
    choices: [
      {
        id: 'sing',
        chance: chance(0.2, { hobbies: { music: 0.008 }, stats: { social: 0.003 } }),
        success: [rep(4), happy(5), hobby('music', 2)],
        failure: [happy(-3), social(1)],
      },
      {
        id: 'comedy',
        chance: chance(0.25, { stats: { social: 0.006 }, traits: { outgoing: 0.1 } }),
        success: [social(5), happy(4)],
        failure: [happy(-3)],
      },
      { id: 'watch', effects: [happy(1)] },
    ],
  },
  {
    id: 'grandparent_story',
    minAge: 12,
    maxAge: 17,
    weight: 6,
    tone: 'good',
    npc: { relation: 'grandparent' },
    effects: [bond('event', 6), know(1), happy(1)],
  },
];
